### ISSUE TITLE
Financial's page 

### ISSUE THREAD

**Issue by RachellCalhoun** [djangogirlscodecamp/lightandleadership#20]
![page2](https://cloud.githubusercontent.com/assets/10239547/13799247/f89552b4-eb60-11e5-8051-c585fb0703c7.jpg)

**Comment by RachellCalhoun** [comment]
It's pretty much the same design as the eduprograms, but there's a strip of color under the header. I'm not sure what'll be in the financial but I'll assume it's text.

**Comment by hassanabidpk** [comment]
I like the social icons down there :+1:

**Comment by RachellCalhoun** [comment]
After asking the school director she said to take out the strip of color in these pages to make them uniform.
