### ISSUE TITLE
Base.html

### ISSUE THREAD

**Issue by RachellCalhoun** [djangogirlscodecamp/lightandleadership#3]
<h3>Base template</h3>

<ol>
<li><h5>Header :</h5>
<p>should be a dark grey/black that's little transparent</p>
<p> the 'take action' should be a  drop down with two choices: Peru or US</p>
<p>donate section should be different color</p></li>
<li><h5>footer: </h5>
<p>the image should be able to be changed by admin as well as text</p></li> 
</ol>

</p>Using block content, create a base for other pages. 

<p>footer:</p>

![llifooter](https://cloud.githubusercontent.com/assets/10239547/12971178/52e4fa62-d0db-11e5-9892-28e5d370a0b1.png)

<p>header with blue background:</p>

![lliheader](https://cloud.githubusercontent.com/assets/10239547/12971177/52e2a73a-d0db-11e5-9fa1-6686022cdd23.png)

<p>header on white background : </p>

![lliheader2](https://cloud.githubusercontent.com/assets/10239547/12971334/5f315cb4-d0dd-11e5-8be4-5d4fb5b407a0.png)

**Comment by JiwonHwang** [comment]
I will do this.

**Comment by RachellCalhoun** [comment]
Should we just put the image in or let them be able to change it?
