### ISSUE TITLE
Our team page

### ISSUE THREAD

**Issue by RachellCalhoun** [djangogirlscodecamp/lightandleadership#6]
<h3>our team:</h3>

<ol>
<li><p>model: img, basetext, us team, peru team, board team</p>
<p> Each team should be all entered at once and separated by commas - use python to split the string. </p></li>
<li>view</li>
<li>html</li>
</ol>

![lliourteam](https://cloud.githubusercontent.com/assets/10239547/12971732/9f916642-d0e1-11e5-8059-720aa8ad340f.png)
![lliourteam2](https://cloud.githubusercontent.com/assets/10239547/12971733/9f94befa-d0e1-11e5-8351-adc2446b4550.png)

**Comment by JiwonHwang** [comment]
me

**Comment by JiwonHwang** [comment]
Need 'About Us' in the ourteam page?

**Comment by JiwonHwang** [comment]
It's just a note for myself to print names like the image. Ignore this. 
1. 
   >>> names = ['a', 'b', 'c']
   >>> for i in names:
   ...     print(i)
   ... 
   a
   b
   c

2.

> > > names= a, b, c
> > >  print (names.split(','))
> > > 'a', 'b', 'c'

def us_team_names(self):
        return self.us_team.split(',')

def peru_team_names(self):
        return self.peru_team.split(',')

**Comment by RachellCalhoun** [comment]
How's it going @JiwonHwang ?
